import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download } from "lucide-react";
import { apiDownload, apiList, apiRequest, hasAnyPermission, hasPermission, startMicrosoftStepUp, type BackendSession } from "../api";
import { displayMoney, displayTitle, idempotencyHeaders, saveDownload, workflowKey } from "./workflow-utils";

export type PayrollRun = { id: string; year: number; month: number; revision: number; status: string; version: number; generatedByUserId: string; payrolls?: Payslip[]; _count?: { payrolls: number } };
type Payslip = { id: string; employeeId: string; year: number; month: number; baseSalary: string; allowances: string; bonuses: string; deductions: string; taxAmount: string; grossPay: string; netPay: string; employee: { employeeCode: string; firstName: string; lastName: string; department?: { id: string; name: string } | null }; payrollRun?: { status: string; revision: number } };
type PayrollDepartment = { id: string; name: string };

export function MyPayslipsPanel({ session, notify }: { session: BackendSession; notify: (message: string) => void }) {
  const payslips = useQuery({ queryKey: workflowKey(session, "my-payslips-self"), queryFn: () => apiList<Payslip>("/payroll/payslips/me?limit=100"), enabled: hasPermission(session, "payroll.self.read_payslip") });
  async function download(id: string) { const file = await apiDownload(`/payroll/payslips/${id}/download`); saveDownload(file.blob, file.fileName); }
  if (!hasPermission(session, "payroll.self.read_payslip")) return null;
  return <section className="panel span-2"><div className="panel-head"><div><h3>My payslips</h3><span>Published, current payslips are available here.</span></div></div>{payslips.isPending ? <p className="muted">Loading payslips…</p> : payslips.isError ? <p className="sync-alert">{payslips.error.message}</p> : <div className="table-wrap"><table><thead><tr><th>Period</th><th>Gross</th><th>Deductions</th><th>Net</th><th></th></tr></thead><tbody>{payslips.data?.map(item => <tr key={item.id}><td>{item.year}-{String(item.month).padStart(2, "0")}</td><td>{displayMoney(item.grossPay)}</td><td>{displayMoney(Number(item.deductions) + Number(item.taxAmount))}</td><td>{displayMoney(item.netPay)}</td><td><button onClick={() => void download(item.id).catch(error => notify(error.message))}><Download size={15} /> PDF</button></td></tr>)}</tbody></table>{!payslips.data?.length && <div className="empty">No published payslips yet.</div>}</div>}</section>;
}

export function PayrollWorkflowPage({ session, notify }: { session: BackendSession; notify: (message: string) => void }) {
  const client = useQueryClient();
  const now = new Date();
  const [period, setPeriod] = useState({ year: now.getFullYear(), month: now.getMonth() + 1 });
  const [reasonAction, setReasonAction] = useState<{ run: PayrollRun; action: "cancel" | "correction" } | null>(null);
  const [reason, setReason] = useState("");
  const [protectedPassword, setProtectedPassword] = useState("");
  const [departmentId, setDepartmentId] = useState("");
  const canReadRuns = hasAnyPermission(session, "payroll.read", "payroll.audit.read");
  const runs = useQuery({ queryKey: workflowKey(session, "payroll-runs"), queryFn: () => apiList<PayrollRun>("/payroll/runs?limit=100"), enabled: canReadRuns });
  const payslips = useQuery({ queryKey: workflowKey(session, "payroll-payslips"), queryFn: () => apiList<Payslip>(hasPermission(session, "payroll.payslip.read_all") ? "/payroll/payslips?limit=100" : "/payroll/payslips/me?limit=100"), enabled: hasAnyPermission(session, "payroll.payslip.read_all", "payroll.self.read_payslip") });
  const departments = useQuery({ queryKey: workflowKey(session, "payroll-departments"), queryFn: () => apiList<PayrollDepartment>("/payroll/departments"), enabled: hasPermission(session, "payroll.export") });
  const refresh = () => Promise.all([
    client.invalidateQueries({ queryKey: workflowKey(session, "payroll-runs") }),
    client.invalidateQueries({ queryKey: workflowKey(session, "payroll-payslips") }),
    client.invalidateQueries({ queryKey: workflowKey(session, "approval-inbox") }),
  ]);
  const generate = useMutation({ mutationFn: () => apiRequest<PayrollRun>("/payroll/runs", { method: "POST", csrfToken: session.csrfToken, headers: idempotencyHeaders(), body: JSON.stringify(period) }), onSuccess: async () => { await refresh(); notify("Payroll run generated."); } });
  const transition = useMutation({
    mutationFn: async ({ run, action, reason: actionReason }: { run: PayrollRun; action: string; reason?: string }) => {
      if (action === "correction" && session.authProvider === "local") {
        if (!protectedPassword) throw new Error("Enter your password for this protected action.");
        await apiRequest("/auth/step-up/local", { method: "POST", csrfToken: session.csrfToken, body: JSON.stringify({ password: protectedPassword }) });
      }
      return apiRequest<PayrollRun>(`/payroll/runs/${run.id}/${action}`, { method: "POST", csrfToken: session.csrfToken, headers: idempotencyHeaders(), body: JSON.stringify({ expectedVersion: run.version, ...(actionReason ? { reason: actionReason } : {}) }) });
    },
    onSuccess: async () => { await refresh(); setReasonAction(null); setReason(""); setProtectedPassword(""); notify("Payroll run updated."); },
  });
  async function download(id: string) { const file = await apiDownload(`/payroll/payslips/${id}/download`); saveDownload(file.blob, file.fileName); }
  async function exportRun(id: string, selectedDepartmentId?: string) { const file = await apiDownload(`/payroll/runs/${id}/export${selectedDepartmentId ? `?departmentId=${encodeURIComponent(selectedDepartmentId)}` : ""}`); saveDownload(file.blob, file.fileName); }

  return <section className="stack">
    {hasPermission(session, "payroll.generate") && <div className="panel"><div className="panel-head"><div><h3>Generate payroll run</h3><span>Attendance, unpaid leave and loans are calculated by the server.</span></div><div className="inline-controls"><select value={period.month} onChange={event => setPeriod(previous => ({ ...previous, month: Number(event.target.value) }))}>{Array.from({ length: 12 }, (_, index) => <option value={index + 1} key={index}>{new Intl.DateTimeFormat(undefined, { month: "long" }).format(new Date(2026, index, 1))}</option>)}</select><input type="number" min={2000} max={2100} value={period.year} onChange={event => setPeriod(previous => ({ ...previous, year: Number(event.target.value) }))} /><button className="primary" disabled={generate.isPending} onClick={() => generate.mutate()}>Generate</button></div></div>{generate.isError && <p className="sync-alert">{generate.error.message}</p>}</div>}
    {canReadRuns && <div className="panel"><div className="panel-head"><div><h3>Payroll runs</h3><span>Approve, publish and mark paid as separate actions.</span></div>{hasPermission(session, "payroll.export") && <label className="compact-control">Export scope<select aria-label="Payroll export department" value={departmentId} onChange={event => setDepartmentId(event.target.value)}><option value="">All departments</option>{departments.data?.map(department => <option value={department.id} key={department.id}>{department.name}</option>)}</select></label>}</div>{runs.isPending ? <p className="muted">Loading payroll runs…</p> : runs.isError ? <p className="sync-alert">{runs.error.message}</p> : <div className="table-wrap"><table><thead><tr><th>Period</th><th>Revision</th><th>Payslips</th><th>Status</th><th>Actions</th></tr></thead><tbody>{runs.data?.map(run => <tr key={run.id}><td>{run.year}-{String(run.month).padStart(2, "0")}</td><td>{run.revision}</td><td>{run._count?.payrolls ?? run.payrolls?.length ?? 0}</td><td><span className="badge neutral">{displayTitle(run.status)}</span></td><td><div className="row-actions">{run.status === "GENERATED" && hasPermission(session, "payroll.generate") && <button onClick={() => transition.mutate({ run, action: "submit" })}>Submit</button>}{run.status === "PENDING_APPROVAL" && hasPermission(session, "payroll.approve") && <button onClick={() => transition.mutate({ run, action: "approve" })}>Approve</button>}{run.status === "APPROVED" && hasPermission(session, "payroll.publish") && <button onClick={() => transition.mutate({ run, action: "publish" })}>Publish</button>}{run.status === "PUBLISHED" && hasPermission(session, "payroll.mark_paid") && <button onClick={() => transition.mutate({ run, action: "mark-paid" })}>Mark paid</button>}{hasPermission(session, "payroll.export") && <button onClick={() => void exportRun(run.id, departmentId || undefined).catch(error => notify(error.message))}>{departmentId ? "Export department" : "Export all"}</button>}{!["PAID", "CANCELLED"].includes(run.status) && hasPermission(session, "payroll.generate") && <button onClick={() => setReasonAction({ run, action: "cancel" })}>Cancel</button>}{hasPermission(session, "payroll.override") && <button onClick={() => setReasonAction({ run, action: "correction" })}>Correction</button>}</div></td></tr>)}</tbody></table></div>}</div>}
    {payslips.isSuccess && <div className="panel"><div className="panel-head"><div><h3>{hasPermission(session, "payroll.payslip.read_all") ? "Payslips" : "My payslips"}</h3><span>Published documents only for self-service.</span></div></div><div className="table-wrap"><table><thead><tr><th>Period</th><th>Employee</th><th>Gross</th><th>Deductions</th><th>Net</th><th></th></tr></thead><tbody>{payslips.data?.map(item => <tr key={item.id}><td>{item.year}-{String(item.month).padStart(2, "0")}</td><td>{item.employee.employeeCode} — {item.employee.firstName} {item.employee.lastName}</td><td>{displayMoney(item.grossPay)}</td><td>{displayMoney(Number(item.deductions) + Number(item.taxAmount))}</td><td>{displayMoney(item.netPay)}</td><td><button onClick={() => void download(item.id).catch(error => notify(error.message))}><Download size={15} /> PDF</button></td></tr>)}</tbody></table></div></div>}
    {reasonAction && <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true"><h2>{displayTitle(reasonAction.action)} payroll run</h2><p>This action keeps historical snapshots and requires an audit reason.</p><label>Reason<textarea autoFocus value={reason} maxLength={1000} onChange={event => setReason(event.target.value)} /></label>{reasonAction.action === "correction" && (session.authProvider === "local" ? <label>Current password<input type="password" autoComplete="current-password" value={protectedPassword} onChange={event => setProtectedPassword(event.target.value)} /></label> : <button type="button" onClick={startMicrosoftStepUp}>Re-authenticate with Microsoft</button>)}<div className="modal-actions"><button onClick={() => setReasonAction(null)}>Cancel</button><button className="primary" disabled={reason.trim().length < 3 || transition.isPending || (reasonAction.action === "correction" && session.authProvider === "local" && !protectedPassword)} onClick={() => transition.mutate({ run: reasonAction.run, action: reasonAction.action, reason: reason.trim() })}>Confirm</button></div>{transition.isError && <p className="sync-alert">{transition.error.message}</p>}</div></div>}
  </section>;
}
