import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download } from "lucide-react";
import { apiDownload, apiList, apiRequest, hasActiveSuperAdminRole, hasAnyPermission, hasPermission, startMicrosoftStepUp, type BackendSession } from "../api";
import { displayMoney, displayTitle, idempotencyHeaders, saveDownload, workflowKey } from "./workflow-utils";

export type PayrollRun = { id: string; year: number; month: number; revision: number; runType?: string; purpose?: string | null; status: string; version: number; generatedByUserId: string; paymentBatchReference?: string | null; payrolls?: Payslip[]; _count?: { payrolls: number } };
type Payslip = { id: string; employeeId: string; year: number; month: number; baseSalary: string; allowances: string; bonuses: string; deductions: string; taxAmount: string; grossPay: string; netPay: string; employee: { employeeCode: string; firstName: string; lastName: string; department?: { id: string; name: string } | null }; payrollRun?: { status: string; revision: number } };
type PayrollDepartment = { id: string; name: string };
type PayrollEmployee = { id: string; employeeCode: string; firstName: string; lastName: string };
type PayrollIssue = { severity: "ERROR" | "WARNING"; code: string; message: string; employeeCode?: string };
type PayrollPreflight = { ready: boolean; runType: string; policy: { prorationBasis: string; requireBankDetails: boolean; requireAttendance: boolean; varianceThreshold: string }; summary: { employees: number; errors: number; warnings: number; grossPay: string; deductions: string; netPay: string; adjustments: number }; issues: PayrollIssue[] };
type PayrollAdjustment = { id: string; employeeId: string; year: number; month: number; direction: string; amount: string; taxable: boolean; description: string; reason: string; appliedPayrollId?: string | null };

export function MyPayslipsPanel({ session, notify }: { session: BackendSession; notify: (message: string) => void }) {
  const payslips = useQuery({ queryKey: workflowKey(session, "my-payslips-self"), queryFn: () => apiList<Payslip>("/payroll/payslips/me"), enabled: Boolean(session.employeeId) && hasPermission(session, "payroll.self.read_payslip") });
  async function download(id: string) { const file = await apiDownload(`/payroll/payslips/${id}/download`); saveDownload(file.blob, file.fileName); }
  if (!hasPermission(session, "payroll.self.read_payslip")) return null;
  if (!session.employeeId) return <section className="panel span-2"><div className="panel-head"><div><h3>My payslips</h3><span>Published, current payslips are available here.</span></div></div><div className="empty">No published payslips yet.</div></section>;
  return <section className="panel span-2"><div className="panel-head"><div><h3>My payslips</h3><span>Published, current payslips are available here.</span></div></div>{payslips.isPending ? <p className="muted">Loading payslips…</p> : payslips.isError ? <p className="sync-alert">{payslips.error.message}</p> : <div className="table-wrap"><table><thead><tr><th>Period</th><th>Gross</th><th>Deductions</th><th>Net</th><th></th></tr></thead><tbody>{payslips.data?.map(item => <tr key={item.id}><td>{item.year}-{String(item.month).padStart(2, "0")}</td><td>{displayMoney(item.grossPay)}</td><td>{displayMoney(Number(item.deductions) + Number(item.taxAmount))}</td><td>{displayMoney(item.netPay)}</td><td><button onClick={() => void download(item.id).catch(error => notify(error.message))}><Download size={15} /> PDF</button></td></tr>)}</tbody></table>{!payslips.data?.length && <div className="empty">No published payslips yet.</div>}</div>}</section>;
}

export function PayrollWorkflowPage({ session, notify }: { session: BackendSession; notify: (message: string) => void }) {
  const client = useQueryClient();
  const requiresStepUp = !hasActiveSuperAdminRole(session);
  const now = new Date();
  const [period, setPeriod] = useState({ year: now.getFullYear(), month: now.getMonth() + 1 });
  const [runType, setRunType] = useState<"REGULAR" | "OFF_CYCLE">("REGULAR");
  const [offCycleEmployeeId, setOffCycleEmployeeId] = useState("");
  const [offCyclePurpose, setOffCyclePurpose] = useState("");
  const [showPreflight, setShowPreflight] = useState(false);
  const [reasonAction, setReasonAction] = useState<{ run: PayrollRun; action: "cancel" | "correction" | "mark-paid" } | null>(null);
  const [reason, setReason] = useState("");
  const [paymentBatchReference, setPaymentBatchReference] = useState("");
  const [protectedPassword, setProtectedPassword] = useState("");
  const [departmentId, setDepartmentId] = useState("");
  const [adjustment, setAdjustment] = useState({ employeeId: "", direction: "EARNING" as "EARNING" | "DEDUCTION", amount: "", taxable: false, description: "", reason: "" });
  const canReadRuns = hasAnyPermission(session, "payroll.read", "payroll.audit.read");
  const runs = useQuery({ queryKey: workflowKey(session, "payroll-runs"), queryFn: () => apiList<PayrollRun>("/payroll/runs"), enabled: canReadRuns });
  const employees = useQuery({ queryKey: workflowKey(session, "payroll-employees"), queryFn: () => apiList<PayrollEmployee>("/employees?limit=1000"), enabled: hasPermission(session, "payroll.generate") });
  const activePeriodRun = runs.data?.find(run => run.year === period.year && run.month === period.month && run.status !== "CANCELLED" && (run.runType ?? "REGULAR") === runType);
  const preflightPath = `/payroll/preflight?year=${period.year}&month=${period.month}&runType=${runType}${runType === "OFF_CYCLE" && offCycleEmployeeId ? `&employeeId=${encodeURIComponent(offCycleEmployeeId)}` : ""}${runType === "OFF_CYCLE" && offCyclePurpose.trim() ? `&purpose=${encodeURIComponent(offCyclePurpose.trim())}` : ""}`;
  const preflight = useQuery({ queryKey: [...workflowKey(session, "payroll-preflight"), period.year, period.month, runType, offCycleEmployeeId, offCyclePurpose], queryFn: () => apiRequest<PayrollPreflight>(preflightPath), enabled: hasPermission(session, "payroll.generate") && !activePeriodRun && (runType === "REGULAR" || Boolean(offCycleEmployeeId && offCyclePurpose.trim().length >= 3)) });
  const payslips = useQuery({ queryKey: workflowKey(session, "payroll-payslips"), queryFn: () => apiList<Payslip>(hasPermission(session, "payroll.payslip.read_all") ? "/payroll/payslips" : "/payroll/payslips/me"), enabled: hasAnyPermission(session, "payroll.payslip.read_all", "payroll.self.read_payslip") });
  const departments = useQuery({ queryKey: workflowKey(session, "payroll-departments"), queryFn: () => apiList<PayrollDepartment>("/payroll/departments"), enabled: hasPermission(session, "payroll.export") });
  const adjustments = useQuery({ queryKey: workflowKey(session, "payroll-adjustments"), queryFn: () => apiList<PayrollAdjustment>("/payroll/adjustments?limit=100"), enabled: hasPermission(session, "payroll.read") });
  const refresh = () => Promise.all([
    client.invalidateQueries({ queryKey: workflowKey(session, "payroll-runs") }),
    client.invalidateQueries({ queryKey: workflowKey(session, "payroll-payslips") }),
    client.invalidateQueries({ queryKey: workflowKey(session, "payroll-adjustments") }),
    client.invalidateQueries({ queryKey: workflowKey(session, "payroll-preflight") }),
    client.invalidateQueries({ queryKey: workflowKey(session, "approval-inbox") }),
  ]);
  const generate = useMutation({ mutationFn: () => apiRequest<PayrollRun>("/payroll/runs", { method: "POST", csrfToken: session.csrfToken, headers: idempotencyHeaders(), body: JSON.stringify({ ...period, runType, ...(runType === "OFF_CYCLE" ? { employeeId: offCycleEmployeeId, purpose: offCyclePurpose.trim() } : {}) }) }), onSuccess: () => { setShowPreflight(false); notify("Payroll run generated."); }, onSettled: refresh });
  const createAdjustment = useMutation({ mutationFn: () => apiRequest<PayrollAdjustment>("/payroll/adjustments", { method: "POST", csrfToken: session.csrfToken, body: JSON.stringify({ ...period, ...adjustment, amount: adjustment.amount, description: adjustment.description.trim(), reason: adjustment.reason.trim() }) }), onSuccess: () => { setAdjustment({ employeeId: "", direction: "EARNING", amount: "", taxable: false, description: "", reason: "" }); notify("Payroll adjustment recorded for the next eligible run."); }, onSettled: refresh });
  const transition = useMutation({
    mutationFn: async ({ run, action, reason: actionReason }: { run: PayrollRun; action: string; reason?: string }) => {
      if (requiresStepUp && action === "correction" && session.authProvider === "local") {
        if (!protectedPassword) throw new Error("Enter your password for this protected action.");
        await apiRequest("/auth/step-up/local", { method: "POST", csrfToken: session.csrfToken, body: JSON.stringify({ password: protectedPassword }) });
      }
      return apiRequest<PayrollRun>(`/payroll/runs/${run.id}/${action}`, { method: "POST", csrfToken: session.csrfToken, headers: idempotencyHeaders(), body: JSON.stringify({ expectedVersion: run.version, ...(actionReason ? { reason: actionReason } : {}), ...(action === "mark-paid" ? { paymentBatchReference: paymentBatchReference.trim() } : {}) }) });
    },
    onSuccess: async () => { await refresh(); setReasonAction(null); setReason(""); setPaymentBatchReference(""); setProtectedPassword(""); notify("Payroll run updated."); },
  });
  async function download(id: string) { const file = await apiDownload(`/payroll/payslips/${id}/download`); saveDownload(file.blob, file.fileName); }
  async function exportRun(id: string, selectedDepartmentId?: string) { const file = await apiDownload(`/payroll/runs/${id}/export${selectedDepartmentId ? `?departmentId=${encodeURIComponent(selectedDepartmentId)}` : ""}`); saveDownload(file.blob, file.fileName); }
  async function exportWps(id: string) { const file = await apiDownload(`/payroll/runs/${id}/wps-export`); saveDownload(file.blob, file.fileName); }

  return <section className="stack">
    {hasPermission(session, "payroll.generate") && <div className="panel"><div className="panel-head"><div><h3>Generate payroll run</h3><span>Component-level pay, attendance, unpaid leave, loans and approved adjustments are calculated by the server.</span></div><div className="inline-controls"><select value={period.month} onChange={event => setPeriod(previous => ({ ...previous, month: Number(event.target.value) }))}>{Array.from({ length: 12 }, (_, index) => <option value={index + 1} key={index}>{new Intl.DateTimeFormat(undefined, { month: "long" }).format(new Date(2026, index, 1))}</option>)}</select><input type="number" min={2000} max={2100} value={period.year} onChange={event => setPeriod(previous => ({ ...previous, year: Number(event.target.value) }))} /><select value={runType} onChange={event => setRunType(event.target.value as "REGULAR" | "OFF_CYCLE")}><option value="REGULAR">Regular payroll</option><option value="OFF_CYCLE">Off-cycle adjustment</option></select></div></div>{runType === "OFF_CYCLE" && <div className="form-grid compact"><label>Employee<select value={offCycleEmployeeId} onChange={event => setOffCycleEmployeeId(event.target.value)}><option value="">Select employee</option>{employees.data?.map(employee => <option value={employee.id} key={employee.id}>{employee.employeeCode} — {employee.firstName} {employee.lastName}</option>)}</select></label><label>Purpose<input maxLength={240} value={offCyclePurpose} onChange={event => setOffCyclePurpose(event.target.value)} placeholder="e.g. approved overtime correction" /></label></div>}<div className="panel-actions"><button className="primary" disabled={Boolean(activePeriodRun) || preflight.isPending || !preflight.data} onClick={() => setShowPreflight(true)}>{activePeriodRun ? "Already generated" : preflight.isPending ? "Checking payroll…" : preflight.data?.ready ? "Review and generate" : "Review preflight errors"}</button>{preflight.isError && <p className="sync-alert">{preflight.error.message}</p>}</div>{preflight.data && <p className={preflight.data.ready ? "muted" : "sync-alert"}>{preflight.data.ready ? `${preflight.data.summary.employees} employees ready · ${preflight.data.summary.warnings} warning(s) require review.` : `${preflight.data.summary.errors} blocking payroll issue(s) found. Review the preview for details.`}</p>}{generate.isError && !activePeriodRun && <p className="sync-alert">{generate.error.message}</p>}</div>}
    {hasPermission(session, "payroll.generate") && <div className="panel"><div className="panel-head"><div><h3>Payroll adjustments</h3><span>Use for approved overtime, corrections and deductions. They are immutable once applied.</span></div></div><div className="form-grid compact"><label>Employee<select value={adjustment.employeeId} onChange={event => setAdjustment(previous => ({ ...previous, employeeId: event.target.value }))}><option value="">Select employee</option>{employees.data?.map(employee => <option value={employee.id} key={employee.id}>{employee.employeeCode} — {employee.firstName} {employee.lastName}</option>)}</select></label><label>Direction<select value={adjustment.direction} onChange={event => setAdjustment(previous => ({ ...previous, direction: event.target.value as "EARNING" | "DEDUCTION" }))}><option value="EARNING">Earning</option><option value="DEDUCTION">Deduction</option></select></label><label>Amount<input type="number" min="0.01" step="0.01" value={adjustment.amount} onChange={event => setAdjustment(previous => ({ ...previous, amount: event.target.value }))} /></label><label>Description<input maxLength={240} value={adjustment.description} onChange={event => setAdjustment(previous => ({ ...previous, description: event.target.value }))} /></label><label>Audit reason<input maxLength={1000} value={adjustment.reason} onChange={event => setAdjustment(previous => ({ ...previous, reason: event.target.value }))} /></label><label className="checkbox-row"><input type="checkbox" checked={adjustment.taxable} onChange={event => setAdjustment(previous => ({ ...previous, taxable: event.target.checked }))} /> Taxable earning</label></div><button disabled={createAdjustment.isPending || !adjustment.employeeId || Number(adjustment.amount) <= 0 || adjustment.description.trim().length < 3 || adjustment.reason.trim().length < 3} onClick={() => createAdjustment.mutate()}>Record adjustment</button>{createAdjustment.isError && <p className="sync-alert">{createAdjustment.error.message}</p>}{adjustments.data?.length ? <div className="table-wrap"><table><thead><tr><th>Period</th><th>Employee</th><th>Direction</th><th>Amount</th><th>Status</th></tr></thead><tbody>{adjustments.data.slice(0, 10).map(item => <tr key={item.id}><td>{item.year}-{String(item.month).padStart(2, "0")}</td><td>{employees.data?.find(employee => employee.id === item.employeeId)?.employeeCode ?? item.employeeId}</td><td>{displayTitle(item.direction)}</td><td>{displayMoney(item.amount)}</td><td>{item.appliedPayrollId ? "Applied" : "Pending"}</td></tr>)}</tbody></table></div> : null}</div>}
    {canReadRuns && <div className="panel"><div className="panel-head"><div><h3>Payroll runs</h3><span>Approve, publish and reconcile payments as separate actions.</span></div>{hasPermission(session, "payroll.export") && <label className="compact-control">Export scope<select aria-label="Payroll export department" value={departmentId} onChange={event => setDepartmentId(event.target.value)}><option value="">All departments</option>{departments.data?.map(department => <option value={department.id} key={department.id}>{department.name}</option>)}</select></label>}</div>{runs.isPending ? <p className="muted">Loading payroll runs…</p> : runs.isError ? <p className="sync-alert">{runs.error.message}</p> : <div className="table-wrap"><table><thead><tr><th>Period</th><th>Type</th><th>Revision</th><th>Payslips</th><th>Status</th><th>Actions</th></tr></thead><tbody>{runs.data?.map(run => <tr key={run.id}><td>{run.year}-{String(run.month).padStart(2, "0")}</td><td>{displayTitle(run.runType ?? "REGULAR")}</td><td>{run.revision}</td><td>{run._count?.payrolls ?? run.payrolls?.length ?? 0}</td><td><span className="badge neutral">{displayTitle(run.status)}</span>{run.paymentBatchReference && <small className="muted"> {run.paymentBatchReference}</small>}</td><td><div className="row-actions">{run.status === "GENERATED" && hasPermission(session, "payroll.generate") && <button onClick={() => transition.mutate({ run, action: "submit" })}>Submit</button>}{run.status === "PENDING_APPROVAL" && hasPermission(session, "payroll.approve") && <button onClick={() => transition.mutate({ run, action: "approve" })}>Approve</button>}{run.status === "APPROVED" && hasPermission(session, "payroll.publish") && <button onClick={() => transition.mutate({ run, action: "publish" })}>Publish</button>}{["APPROVED", "PUBLISHED", "PAID"].includes(run.status) && hasPermission(session, "payroll.mark_paid") && <button onClick={() => void exportWps(run.id).catch(error => notify(error.message))}>WPS payment file</button>}{run.status === "PUBLISHED" && hasPermission(session, "payroll.mark_paid") && <button onClick={() => setReasonAction({ run, action: "mark-paid" })}>Reconcile paid</button>}{hasPermission(session, "payroll.export") && <button onClick={() => void exportRun(run.id, departmentId || undefined).catch(error => notify(error.message))}>{departmentId ? "Export department" : "Export all"}</button>}{!["PAID", "CANCELLED"].includes(run.status) && hasPermission(session, "payroll.generate") && <button onClick={() => setReasonAction({ run, action: "cancel" })}>Cancel</button>}{hasPermission(session, "payroll.override") && <button onClick={() => setReasonAction({ run, action: "correction" })}>Correction</button>}</div></td></tr>)}</tbody></table>{!runs.data?.length && <div className="empty">No payroll runs.</div>}</div>}</div>}
    {payslips.isSuccess && <div className="panel"><div className="panel-head"><div><h3>{hasPermission(session, "payroll.payslip.read_all") ? "Payslips" : "My payslips"}</h3><span>Published documents only for self-service.</span></div></div><div className="table-wrap"><table><thead><tr><th>Period</th><th>Employee</th><th>Gross</th><th>Deductions</th><th>Net</th><th></th></tr></thead><tbody>{payslips.data?.map(item => <tr key={item.id}><td>{item.year}-{String(item.month).padStart(2, "0")}</td><td>{item.employee.employeeCode} — {item.employee.firstName} {item.employee.lastName}</td><td>{displayMoney(item.grossPay)}</td><td>{displayMoney(Number(item.deductions) + Number(item.taxAmount))}</td><td>{displayMoney(item.netPay)}</td><td><button onClick={() => void download(item.id).catch(error => notify(error.message))}><Download size={15} /> PDF</button></td></tr>)}</tbody></table>{!payslips.data?.length && <div className="empty">No payslips.</div>}</div></div>}
    {showPreflight && preflight.data && <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true"><h2>Payroll preflight review</h2><p>{preflight.data.summary.employees} employees · Gross {displayMoney(preflight.data.summary.grossPay)} · Deductions {displayMoney(preflight.data.summary.deductions)} · Net {displayMoney(preflight.data.summary.netPay)}</p><p className="muted">Policy: {displayTitle(preflight.data.policy.prorationBasis)} · bank details {preflight.data.policy.requireBankDetails ? "required" : "warning"} · attendance {preflight.data.policy.requireAttendance ? "required" : "warning"}.</p>{preflight.data.issues.length ? <ul className="workflow-issues">{preflight.data.issues.slice(0, 15).map((issue, index) => <li className={issue.severity === "ERROR" ? "sync-alert" : "muted"} key={`${issue.code}-${index}`}>{issue.severity === "ERROR" ? "Blocking" : "Warning"}: {issue.message}</li>)}</ul> : <p className="muted">No exceptions found.</p>}<div className="modal-actions"><button onClick={() => setShowPreflight(false)}>Back</button><button className="primary" disabled={!preflight.data.ready || generate.isPending} onClick={() => generate.mutate()}>{generate.isPending ? "Generating…" : "Confirm generation"}</button></div>{generate.isError && <p className="sync-alert">{generate.error.message}</p>}</div></div>}
    {reasonAction && <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true"><h2>{displayTitle(reasonAction.action)} payroll run</h2><p>{reasonAction.action === "mark-paid" ? "Record the bank or payment batch reference before marking every payslip paid." : "This action keeps historical snapshots and requires an audit reason."}</p>{reasonAction.action === "mark-paid" && <label>Payment batch reference<input autoFocus maxLength={120} value={paymentBatchReference} onChange={event => setPaymentBatchReference(event.target.value)} placeholder="Bank or WPS batch reference" /></label>}<label>Reason<textarea autoFocus={reasonAction.action !== "mark-paid"} value={reason} maxLength={1000} onChange={event => setReason(event.target.value)} /></label>{requiresStepUp && reasonAction.action === "correction" && (session.authProvider === "local" ? <label>Current password<input type="password" autoComplete="current-password" value={protectedPassword} onChange={event => setProtectedPassword(event.target.value)} /></label> : <button type="button" onClick={startMicrosoftStepUp}>Re-authenticate with Microsoft</button>)}<div className="modal-actions"><button onClick={() => setReasonAction(null)}>Cancel</button><button className="primary" disabled={transition.isPending || (reasonAction.action === "mark-paid" ? paymentBatchReference.trim().length < 3 : reason.trim().length < 3) || (requiresStepUp && reasonAction.action === "correction" && session.authProvider === "local" && !protectedPassword)} onClick={() => transition.mutate({ run: reasonAction.run, action: reasonAction.action, reason: reason.trim() })}>Confirm</button></div>{transition.isError && <p className="sync-alert">{transition.error.message}</p>}</div></div>}
  </section>;
}
