import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, Pencil, Plus, Star } from "lucide-react";
import { apiPage, apiRequest, hasAnyPermission, hasPermission, type BackendSession } from "../api";
import type { EmployeeRecord } from "../data";
import { Dialog } from "../dialog";
import { Pagination } from "../pagination";
import { displayDate, displayTitle, workflowKey } from "./workflow-utils";
import { ServiceRequestsPanel } from "./service-requests";

type Notify = (message: string) => void;
type EmployeeSummary = { id: string; employeeCode: string; firstName: string; lastName: string; email: string };
type PageMeta = { total: number; page: number; limit: number; totalPages: number };

function employeeLabel(employee: EmployeeRecord) { return `${employee.fields["Employee Code"]} — ${employee.fields["Full Name"]}`; }
function errorMessage(error: unknown) { return error instanceof Error ? error.message : "Something went wrong."; }

type Review = { id: string; employeeId: string; reviewerId: string; reviewPeriodStart: string; reviewPeriodEnd: string; rating: number | string; goals?: string; strengths?: string; improvements?: string; comments?: string; status: "DRAFT" | "SUBMITTED" | "ACKNOWLEDGED" | "CLOSED"; employee: EmployeeSummary; reviewer: EmployeeSummary };

export function PerformancePage({ session, employees, notify }: { session: BackendSession; employees: EmployeeRecord[]; notify: Notify }) {
  const client = useQueryClient(); const [page, setPage] = useState(1); const [editing, setEditing] = useState<Review | "new" | null>(() => window.location.hash === "#new" ? "new" : null); const canManage = hasAnyPermission(session, "performance.team.manage", "performance.management.manage", "performance.hr.manage"); const hr = hasPermission(session, "performance.hr.manage");
  const reviews = useQuery({ queryKey: [...workflowKey(session, "performance-reviews"), page], queryFn: () => apiPage<Review, PageMeta>(`/performance-reviews?page=${page}&limit=20`) });
  const remove = useMutation({ mutationFn: (id: string) => apiRequest(`/performance-reviews/${id}`, { method: "DELETE", csrfToken: session.csrfToken }), onSuccess: async () => { await client.invalidateQueries({ queryKey: workflowKey(session, "performance-reviews") }); notify("Performance review archived."); } });
  return <div className="experience-page"><section className="feature-heading"><div><span className="eyebrow">Growth · Performance</span><h2>Performance reviews</h2><p>Goals, feedback and ratings through the existing scoped review workflow.</p></div>{canManage && <button className="primary" onClick={() => setEditing("new")}><Plus size={16} /> New review</button>}</section>
    {reviews.isPending ? <PageState label="Loading performance reviews…" /> : reviews.isError ? <PageState error={reviews.error.message} /> : <div className="review-grid">{reviews.data?.data.map(review => <article className="review-card" key={review.id}><div className="review-card__top"><div><span className="eyebrow">{displayTitle(review.status)}</span><h3>{review.employee.firstName} {review.employee.lastName}</h3><p>{displayDate(review.reviewPeriodStart)} – {displayDate(review.reviewPeriodEnd)}</p></div><div className="rating-score"><Star size={17} fill="currentColor" /> {Number(review.rating).toFixed(1)}</div></div><div className="review-copy"><ReviewField label="Goals" value={review.goals} /><ReviewField label="Strengths" value={review.strengths} /><ReviewField label="Improvements" value={review.improvements} /><ReviewField label="Comments" value={review.comments} /></div><footer><span>Reviewer: {review.reviewer.firstName} {review.reviewer.lastName}</span>{canManage && <div className="row-actions"><button onClick={() => setEditing(review)}><Pencil size={14} /> Edit</button>{hr && <button className="danger-outline" disabled={remove.isPending} onClick={() => window.confirm("Archive this performance review?") && remove.mutate(review.id)}><Archive size={14} /> Archive</button>}</div>}</footer></article>)}{!reviews.data?.data.length && <PageState label="No performance reviews are visible in your scope." />}</div>}
    <Pagination total={reviews.data?.meta?.total ?? 0} page={page} limit={20} totalPages={reviews.data?.meta?.totalPages ?? 1} label="reviews" onPage={setPage} />
    {editing && <ReviewDialog value={editing === "new" ? undefined : editing} employees={employees} session={session} hr={hr} close={() => setEditing(null)} done={async () => { setEditing(null); await client.invalidateQueries({ queryKey: workflowKey(session, "performance-reviews") }); notify("Performance review saved."); }} />}
  </div>;
}

function ReviewField({ label, value }: { label: string; value?: string }) { return value ? <div><strong>{label}</strong><p>{value}</p></div> : null; }
function ReviewDialog({ value, employees, session, hr, close, done }: { value?: Review; employees: EmployeeRecord[]; session: BackendSession; hr: boolean; close: () => void; done: () => Promise<void> }) {
  const today = new Date(); const year = today.getFullYear(); const [form, setForm] = useState({ employeeId: value?.employeeId ?? "", reviewPeriodStart: value?.reviewPeriodStart.slice(0, 10) ?? `${year}-01-01`, reviewPeriodEnd: value?.reviewPeriodEnd.slice(0, 10) ?? `${year}-12-31`, rating: Number(value?.rating ?? 3), goals: value?.goals ?? "", strengths: value?.strengths ?? "", improvements: value?.improvements ?? "", comments: value?.comments ?? "", status: value?.status ?? "DRAFT" }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function save() { setBusy(true); setError(""); try { await apiRequest(value ? `/performance-reviews/${value.id}` : "/performance-reviews", { method: value ? "PATCH" : "POST", csrfToken: session.csrfToken, body: JSON.stringify(form) }); await done(); } catch (error) { setError(errorMessage(error)); } finally { setBusy(false); } }
  const statuses = hr ? ["DRAFT", "SUBMITTED", "ACKNOWLEDGED", "CLOSED"] : ["DRAFT", "SUBMITTED"];
  return <Dialog title={value ? "Edit performance review" : "New performance review"} onClose={close}><div className="form-grid"><label className="span-2">Employee<select autoFocus value={form.employeeId} onChange={event => setForm(current => ({ ...current, employeeId: event.target.value }))}><option value="">Select employee</option>{employees.map(employee => <option value={employee.id} key={employee.id}>{employeeLabel(employee)}</option>)}</select></label><label>Period start<input type="date" value={form.reviewPeriodStart} onChange={event => setForm(current => ({ ...current, reviewPeriodStart: event.target.value }))} /></label><label>Period end<input type="date" value={form.reviewPeriodEnd} onChange={event => setForm(current => ({ ...current, reviewPeriodEnd: event.target.value }))} /></label><label>Rating (0–5)<input type="number" min="0" max="5" step="0.1" value={form.rating} onChange={event => setForm(current => ({ ...current, rating: Number(event.target.value) }))} /></label><label>Status<select value={form.status} onChange={event => setForm(current => ({ ...current, status: event.target.value as typeof form.status }))}>{statuses.map(status => <option key={status}>{status}</option>)}</select></label>{(["goals", "strengths", "improvements", "comments"] as const).map(field => <label className="span-2" key={field}>{field[0].toUpperCase() + field.slice(1)}<textarea maxLength={5000} value={form[field]} onChange={event => setForm(current => ({ ...current, [field]: event.target.value }))} /></label>)}</div>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" disabled={!form.employeeId || busy} onClick={() => void save()}>{busy ? "Saving…" : "Save review"}</button></div></Dialog>;
}

export function CertificatesPage({ session, notify }: { session: BackendSession; notify: Notify }) { return <div className="experience-page"><section className="feature-heading"><div><span className="eyebrow">Communication · Certificates</span><h2>Certificates and letters</h2><p>Request, generate, approve, publish, track versions and download authorized documents.</p></div></section><div className="workflow-page-grid"><ServiceRequestsPanel session={session} notify={notify} /></div></div>; }

function PageState({ label, error }: { label?: string; error?: string }) { return <div className={`page-state${error ? " is-error" : ""}`} role={error ? "alert" : "status"}>{error ?? label}</div>; }
