import { useEffect, useMemo, useRef, useState } from "react";
import { CheckCircle2, Megaphone, Plus, Search, UserPlus, X } from "lucide-react";

export type CommandItem = { id: string; label: string; hint: string; keywords?: string; onSelect: () => void };
export type QuickAction = { id: string; label: string; hint: string; kind: "employee" | "announcement" | "approval"; onSelect: () => void };

const actionIcon = { employee: UserPlus, announcement: Megaphone, approval: CheckCircle2 };

export function CommandTrigger({ open }: { open: () => void }) {
  return <button className="command-trigger" type="button" onClick={open} aria-haspopup="dialog"><Search size={17} /><span>Search people or actions</span><kbd>Ctrl K</kbd></button>;
}

export function CommandPalette({ open, items, pageLabel, close, searchPage }: { open: boolean; items: CommandItem[]; pageLabel: string; close: () => void; searchPage: (query: string) => void }) {
  const [query, setQuery] = useState(""); const [active, setActive] = useState(0); const inputRef = useRef<HTMLInputElement>(null); const paletteRef = useRef<HTMLElement>(null); const returnFocusRef = useRef<HTMLElement | null>(null);
  const filtered = useMemo(() => { const needle = query.trim().toLocaleLowerCase(); return needle ? items.filter(item => `${item.label} ${item.hint} ${item.keywords ?? ""}`.toLocaleLowerCase().includes(needle)).slice(0, 12) : items.slice(0, 12); }, [items, query]);
  useEffect(() => { if (!open) return; returnFocusRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setQuery(""); setActive(0); const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; window.setTimeout(() => inputRef.current?.focus(), 0); return () => { document.body.style.overflow = overflow; window.setTimeout(() => returnFocusRef.current?.isConnected && returnFocusRef.current.focus(), 0); }; }, [open]);
  useEffect(() => setActive(0), [query]);
  if (!open) return null;
  function choose(item?: CommandItem) { if (item) item.onSelect(); else if (query.trim()) searchPage(query.trim()); close(); }
  return <div className="command-scrim" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) close(); }}><section ref={paletteRef} className="command-palette" role="dialog" aria-modal="true" aria-labelledby="command-title" onKeyDown={event => { if (event.key === "Escape") close(); if (event.key === "Tab") { const focusable = [...(paletteRef.current?.querySelectorAll<HTMLElement>('input, button:not([disabled]), [href], [tabindex]:not([tabindex="-1"])') ?? [])]; if (focusable.length) { const edge = event.shiftKey ? focusable[0] : focusable.at(-1); if (document.activeElement === edge) { event.preventDefault(); (event.shiftKey ? focusable.at(-1) : focusable[0])?.focus(); } } } if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); setActive(index => (index + (event.key === "ArrowDown" ? 1 : -1) + Math.max(filtered.length, 1)) % Math.max(filtered.length, 1)); } if (event.key === "Enter") { event.preventDefault(); choose(filtered[active]); } }}><header><Search size={20} /><label className="sr-only" htmlFor="command-search" id="command-title">Search modules and actions</label><input ref={inputRef} id="command-search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Type a page, person or action…" /><button className="icon-button" aria-label="Close command palette" onClick={close}><X size={17} /></button></header><div className="command-results" role="listbox" aria-label="Commands">{filtered.map((item, index) => <button role="option" aria-selected={active === index} className={active === index ? "active" : ""} key={item.id} onMouseEnter={() => setActive(index)} onClick={() => choose(item)}><span><strong>{item.label}</strong><small>{item.hint}</small></span><kbd>↵</kbd></button>)}{query.trim() && <button className={!filtered.length ? "active" : ""} onClick={() => choose()}><span><strong>Search {pageLabel}</strong><small>Filter the current page for “{query.trim()}”</small></span><kbd>↵</kbd></button>}{!filtered.length && !query.trim() && <p>No commands available.</p>}</div><footer><span><kbd>↑</kbd><kbd>↓</kbd> navigate</span><span><kbd>Esc</kbd> close</span></footer></section></div>;
}

export function QuickCreateMenu({ actions }: { actions: QuickAction[] }) {
  const [open, setOpen] = useState(false); const rootRef = useRef<HTMLDivElement>(null); const triggerRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (!open) return; rootRef.current?.querySelector<HTMLButtonElement>("[role=menuitem]")?.focus(); const outside = (event: PointerEvent) => { if (!rootRef.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("pointerdown", outside); return () => document.removeEventListener("pointerdown", outside); }, [open]);
  if (!actions.length) return null;
  return <div className="quick-create" ref={rootRef}><button ref={triggerRef} className="primary quick-create__trigger" aria-label="Quick create" aria-haspopup="menu" aria-expanded={open} onClick={() => setOpen(value => !value)}><Plus size={17} /> <span>Quick create</span></button>{open && <div className="quick-create__menu" role="menu" onKeyDown={event => { const menuItems = [...(rootRef.current?.querySelectorAll<HTMLButtonElement>('[role="menuitem"]') ?? [])]; const index = menuItems.indexOf(document.activeElement as HTMLButtonElement); if (event.key === "Escape") { setOpen(false); triggerRef.current?.focus(); } else if (["ArrowDown", "ArrowUp", "Home", "End"].includes(event.key) && menuItems.length) { event.preventDefault(); const next = event.key === "Home" ? 0 : event.key === "End" ? menuItems.length - 1 : (index + (event.key === "ArrowDown" ? 1 : -1) + menuItems.length) % menuItems.length; menuItems[next].focus(); } }}><span className="eyebrow">Create new</span>{actions.map(action => { const Icon = actionIcon[action.kind]; return <button role="menuitem" key={action.id} onClick={() => { setOpen(false); action.onSelect(); }}><Icon size={17} /><span><strong>{action.label}</strong><small>{action.hint}</small></span></button>; })}</div>}</div>;
}
