ALTER TABLE "SalaryRecord"
  ADD COLUMN "hra" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "conveyance" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "mobile" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "food" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "fuel" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "other" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "grossAdjustment" DECIMAL(12,2) NOT NULL DEFAULT 0;

ALTER TABLE "EmployeeBenefitProfile"
  ADD COLUMN "companyConveyance" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "companyFuel" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "companyOther" BOOLEAN NOT NULL DEFAULT false;
